### ISSUE TITLE
Quest book error

### ISSUE THREAD

**Issue by BigAngelUK** [benbenlaw/techopolis#10]
Tier 2 miner quest has cinnabar showing red on metal scanner and also Iron showing red on a metal scanner one has got to be incorrect

**Comment by benbenlaw** [comment]
the information is actually correct, however i didnt notice that they were the basically the same. In A6.0 cinnabar has been moved to the mineral finder. This will remove the 2 red colours showing on the metal finder making it easier to find either hematite or cinnabar
