### ISSUE TITLE
Techopolis Oneblock

### ISSUE THREAD

**Issue by DarkLordShiro** [benbenlaw/techopolis#15]
Maybe i am not seeing it but there is no way to get lava to use early game besides using the few blocks that are provided for cobble gen.

**Comment by LotP1** [comment]
If you've enabled skyblock-mode you can get lava by smelting a ceramic bucket in a redstone furnace

**Comment by DarkLordShiro** [comment]
oh thanks...is that mentioned anywhere?

**Comment by benbenlaw** [comment]
inside the techopolis guide book
