### ISSUE TITLE
recipes for the finder items

### ISSUE THREAD

**Issue by sebtech33** [benbenlaw/techopolis#20]
I have watch nik and issac's playthrough and they use drit and charcoal to make the finder items, but when i try to use that recipe it doesnt work either in the normal crafting table or the tinker's table.

any help would be nice :)

running on a server with on B9

**Comment by iInFiniTyyy** [comment]
Are you sure you've enabled skyblock recipes?

**Comment by sebtech33** [comment]
oh you need to do that.. i just tossed that after i created a skyblock world.. but if thats the issue i can manage. Thanks for the quick reply :)

**Comment by iInFiniTyyy** [comment]
No problem! :)

**Comment by iInFiniTyyy** [comment]
#closed
