### ISSUE TITLE
SkyBlock clay problem

### ISSUE THREAD

**Issue by Mordrik** [benbenlaw/techopolis#21]
Hello 

I just instaled the modpack en after a while i couln't advance in the quest because we can't make clay, in youtub videos they do it with dirt, but i think it was remouved, si the only way in sky block to make clay is with grout, but for that i need clay... so kind of stuck in a circle there.

**Comment by moody69420** [comment]
you should read the starting quests     https://gyazo.com/3570aa6b37bd04c42b531fd3e6c2034b

**Comment by CharZinta** [comment]
I second the motion
SAND 
https://user-images.githubusercontent.com/8332467/151715335-ecbd053f-19e8-49c9-bb28-55f1b7e593b6.png

GRAVEL
https://user-images.githubusercontent.com/8332467/151715394-23ca2bd0-81db-41a3-b6b4-f3a0d1df51f0.png

cobble is in the "auto cobble maker" the island comes with. that 2 of the 3 items you need for grout. 

Clay is dirt in a pulverize, which you get with the island
read the quests, follow the quests

**Comment by Mordrik** [comment]
Sorry but the pulverizer dont accept the dirt

**Comment by Mordrik** [comment]
never mind i found how, thanks

**Comment by CharZinta** [comment]
if your satisfied with the process. Please close ticket as complete.

Thanks
