### ISSUE TITLE
Compact Drawers Oak Logs Copper Issue

### ISSUE THREAD

**Issue by money08** [benbenlaw/techopolis#22]
![Screenshot_38](https://user-images.githubusercontent.com/16907513/151849485-423b78dd-762c-4d18-bf94-19a5d9b11418.png)

How i make it or what happend here.

Put in an empty Compact Drawer some Copper Ingots
Remove the Copper that the Drawer is empty.
Put Oka Log in it Target the Left Small Thing on it.
Now You have this Oak Log into Copper

**Comment by benbenlaw** [comment]
what version are you on?

**Comment by money08** [comment]
B9.0 SkyBlock

**Comment by money08** [comment]
Test it more it works with all ingots. 
Put any number of ingots in take it out.
Then put 1 Stack of Oak Log(Stack is important) aim bottom left slot when it not work take it out aim botton right.

**Comment by benbenlaw** [comment]
fixed in B10.0
