### ISSUE TITLE
Glitchy Resource combiner

### ISSUE THREAD

**Issue by benbenlaw** [benbenlaw/techopolis#24]
visual bugs with resource combiner see:
https://youtu.be/A3nBVqLIyis?t=3045

**Comment by benbenlaw** [comment]
mod maker aware fix ongoing

**Comment by benbenlaw** [comment]
may now be fixed if not will reopen

**Comment by Moutard3** [comment]
I still have this problem in 2.0

**Comment by benbenlaw** [comment]
maybe fixed in version 3.0
