### ISSUE TITLE
Mining sand in skyblock mode

### ISSUE THREAD

**Issue by DaveLo** [benbenlaw/techopolis#25]
Having trouble mining a 5x5 of sand, trying to automate glass production for crystalline.  I think it should be mineable (shows under the $miner search in JEI). 

I've tried all the tricks I can think of and used tier 1-3 miners (I'm detouring into heavy automation before pushing for the next tier)

I also asked in the [discord](https://discord.com/channels/716249661798612992/890632399933812816/938805665156173895), but the only suggestion was to use grout which isn't really a solution just a workaround.

As a sidenote, this is definitely my favorite pack I've played in a long while :) Thanks for all the hard work making a fun progression/automation based game

**Comment by benbenlaw** [comment]
grout is the way to do it, thanks for the nice message :)

**Comment by DaveLo** [comment]
So the block miner stuff is not accurate or is there a list of blocks that can be mined that way? (thinking of mining some colored terracotta for base accents ;p)

**Comment by benbenlaw** [comment]
yeah not sure why its showing sand, terracotta does work though

**Comment by DaveLo** [comment]
Ok, awesome. Thanks for the help!
