### ISSUE TITLE
[B9.0] Basic Mob Absorber farm

### ISSUE THREAD

**Issue by GamertechAU** [benbenlaw/techopolis#26]
The basic mob farm listed in the Techopolis guide book using passive mobs has a couple of issues.

The schematic requires grass blocks, but the setup breaks frequently due to the mobs (sheep mainly) eating the grass and turning a block into dirt.

-Could be fixed by making both grass and dirt acceptable.

Also, the absorber has a range of 4x4, while the fenced area is 5x5. If you've only got a few mobs and they're at the edge of the enclosure against the fence, it also stops working until they move back.

**Comment by GamertechAU** [comment]
Adding to this, there doesn't seem to be any way to power/empty the advanced (sheetmetal) mob absorber.

Adding a cable/flux plug etc into the room breaks the schematic and prevents it from working.

**Comment by stripeyhorse** [comment]
im on B10 and absorder works fine. I ever have a couple on top of spawners i found while flying about. I skipped the base level one and use the 2nd tier one. Still very hard to get blaze rods thou

**Comment by benbenlaw** [comment]
this whole system is changing in B11.0
