### ISSUE TITLE
Potion of Flight causes Internal Server Error

### ISSUE THREAD

**Issue by Omega172** [benbenlaw/techopolis#28]
Hello I attempted to make the potion of flight on my Techopolis multiplayer server but upon the double tapping space to fly the server kicks you with the error message "Internal Server Error" this kick will happen to any player who attempts to fly that has consumed the potion. 

The log:
[latest.log](https://github.com/benbenlaw/techopolis/files/8009244/latest.log)

**Comment by Ratomas** [comment]
I am seeing this same issue since updating to B10.0

**Comment by LotP1** [comment]
this has been an issue since the mod was added and it only happens on servers btw.
B11 is going to provide an alternative method for flying.

**Comment by benbenlaw** [comment]
mod removed alternative coming
