### ISSUE TITLE
Copper ingot changes to "Tinkers Construct" when placed in inverntory

### ISSUE THREAD

**Issue by CroxtonHale** [benbenlaw/techopolis#30]
So when I cast the copper ingot in the smeltery it gets casted as "Mekanism" copper, but when I move it to my inventory it changes into  "Tinkers Construct" copper which isn't applicable in the recipes that requires copper, therefore I can't make any conveyer belts

**Comment by CroxtonHale** [comment]
It was a mistake on my side, I had the kubejs folder mixed with previous packs. When I deleted my old kubejs folder and replaced it with the one ffrom the pack it worked. So there is no issue here thanks

**Comment by LotP1** [comment]
we recommend using mod loaders such as GDLauncher, MultiMC and CurseForge to make keeping track of packs much easier.
Some mod loaders, like GDL, don't even require you to open the vanilla launcher to launch packs anymore.
