### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by Asmodeus-69** [benbenlaw/techopolis#33]
I just started playing the pack using version B11 in skyblock mode. I am trying to make tinkers patterns and there is a recipe conflict with Macaw's Roofs. I have tried different locations on the crafting table and shift clicking from JEI and still get the oak planks roof cube.

**Comment by Scyriate** [comment]
There is this little arrow loop button above the crafting output, it lets you choose a recipe out of conflicting ones.

**Comment by Asmodeus-69** [comment]
Got it, haven't seen that before. Thanks.
