### ISSUE TITLE
Techopolis Guide Book references nonexistent potion.

### ISSUE THREAD

**Issue by wally314garcia** [benbenlaw/techopolis#34]
Modpack version B11.0
Mode: Skyblock mode

The Techopolis Guide Book references "Flight Potions" under Skyblock Mode > Recipe Changes. Searching JEI for "flight" does not show any flight potion. Searching JEI for "potion" also does not show any flight potion.

Tested in non-skyblock mode as well.
Tested in game created from previous modpack version and in new game created in version B11.0.

**Comment by oenone** [comment]
Flight potion was recently removed, I think B11.0 was the first version without. It got replaced with Balanced Flight. The Guide Book in B12.0 doesn't mention it any more, so it should be fixed.
