### ISSUE TITLE
Chest recipe is inconsistent.

### ISSUE THREAD

**Issue by wally314garcia** [benbenlaw/techopolis#36]
Pack version: B11.0
Mode: Normal and Skyblock

Wood logs give 2 plank each, so it is assumed that 8 wood logs would equal 16 planks.

16 planks can be used to craft 2 chests.

However, 8 wood logs can be used to craft 4 chests.

Crafting chests with wood logs should only give 2 chests to keep the ratio of logs to wood planks consistent between chest recipes.

**Comment by LotP1** [comment]
not a bug
chests can't be used to create planks, so Ben said the logs recipe is fine as it is.

**Comment by DasBrain** [comment]
If this is a problem, then the opposite could be done:  
8x Planks -> 2x Chests.
¯\\_(ツ)_/¯

**Comment by oenone** [comment]
you can turn one log into four or even six planks later using machines, so I don't think this is that relevant. It saves you a few trees at the beginning, but later you won't notice.

**Comment by benbenlaw** [comment]
indended
