### ISSUE TITLE
Crafting blackstone in skyblock mode

### ISSUE THREAD

**Issue by Kylecoler** [benbenlaw/techopolis#39]
while I know I can buy the basic flight anchor from the trader, I figure since it is possible for me to craft the flight wing latter on I should be able to craft the anchor as well.

**Comment by benbenlaw** [comment]
blackstone is obtainable from the nether

**Comment by Kylecoler** [comment]
I didn't realize there was another way to the nether dimension other then the vanilla portal, my bad.
