### ISSUE TITLE
Resource combiner fails to make first tier techium ingots

### ISSUE THREAD

**Issue by realh** [benbenlaw/techopolis#42]
I've built a resource combiner, hooked it up to power, added 16 of each required item in the techium ingot recipe and filled it with water, but it just stays idle. This is in versions B12 and B13 in Linux with MultiMC.

**Comment by CharZinta** [comment]
Please reread the recipe requirements.  all items are not 16, for example, bronze is 32, so is stone. If this solves your issue please close the ticket as solved. IF not please update the ticket.

thank you

**Comment by realh** [comment]
Thanks, I missed that. I had even tried with a full stack of some of the resources, but didn't have as many as 32 bronze ingots in my inventory at that time.
