### ISSUE TITLE
Can't get the t1 miner to mine cobble/stone, tin/copper quest bugged

### ISSUE THREAD

**Issue by salvite** [benbenlaw/techopolis#48]
I've created the 5x5x5 block for both cobblestone and normal stone and placed the t1 miner in the center cube just like my other miners. However, only the cobblestone and stone miners aren't working. I've attempted to make them 6x6x6, nothing i've done works. Also, though I was able to obtain tin and copper ingots, the quests don't show as competed.

**Comment by moody69420** [comment]
first cobblestone cannot been mined via miner, second stone types need a stone miner, third u must complete the prereqs for the quests.
should read the quests and the techopolis book.

**Comment by salvite** [comment]
Okay, fixed my miner and it is working now. After closing out the game and making some more tin/copper from dust I got the achievements.
