### ISSUE TITLE
pickaxe breaks after using pickaxe

### ISSUE THREAD

**Issue by PandaGamersHDNL** [benbenlaw/techopolis#53]
in version 3.0 after using FTB ultimine the pickaxe itself doesn't give you the ores anymore when breaking the ore unless you use ftb ultimine again. when testing it only happened with the platinum and the elite technium pickaxe but i haven't tried all the ores just aluminum with the advanced one and assorted crystal with the elite pickaxe

**Comment by moody69420** [comment]
Works fine for me I never bought ores

**Comment by PandaGamersHDNL** [comment]
restarting my laptop seemed to have resolved the issue
