### ISSUE TITLE
Drawer Controller causing lag.

### ISSUE THREAD

**Issue by kalutro** [benbenlaw/techopolis#57]
I am not sure if this is a mod issue or a pack issue. I opened an issue with the mod: https://github.com/jaquadro/StorageDrawers/issues/1049#issue-1417302764

**Comment by LotP1** [comment]
definitely a mod issue.
it's probably caused by the mekanism pipe trying to interact with the drawer.
also 247 microseconds isn't that bad for a storage controller.

**Comment by kalutro** [comment]
I thought it was a mod issue, though I wasn't sure. I thought it may have been the pipe, but this happens with the controller connected directly to an IE Crusher (sitting next to the output, no pipe) and even just sitting not accepting any items.

I agree 247 microseconds isn't a lot, but they were the only blocks even close to that value. My FPS drops from steady 60 to around 25 when in their presence.

**Comment by LotP1** [comment]
if your fps drops to 25 near it there's definitely something else wrong.
the 247 microseconds are tick lag, which doesn't impact fps lag much, unless your cpu is overloaded.
Also looking at the screenshot your combined tick delay of all the blocks is less than 1 ms, which should allow up to 1000+ fps, meaning that it's something else render related that's causing issues.
what are your pc specs?

**Comment by kalutro** [comment]
I hope it's not my PC. i7-6700k with GTX 1080 running @ 2560x1017 (windowed)
I'll attach a shot of my F3.

I think I know what is causing the spikes. Whenever GC happens I get the huge spike. I am wondering why my memory is filling up so fast, though. It goes from 19% to 56% (~2100MB to 6100MB) in about ten seconds. I play single player although I do Open to LAN so I can leave my game running in the background. Would that be an issue?

Here is the shot of my F3:

![2022-10-20_18 01 57](https://user-images.githubusercontent.com/69569507/197087585-8be95b10-460b-4478-b45f-085b3b22df53.png)

**Comment by kalutro** [comment]
It seems it was Mekanism pipes causing the frame drops. I switched to XNet where I could and saw an immediate change. It could still be my ancient PC, but this fixed it for now.
