### ISSUE TITLE
Server cannot connect

### ISSUE THREAD

**Issue by QQQQQQNB** [benbenlaw/techopolis#58]
2.0 server pack, 2.0 modpack. "Connection closed - mismatched mod channel list" will be displayed for each connection

Because of the characteristics of serverpack, I cannot compare the mods list of serverpack and modpack. But I swear I never moved the mods folder. The strange thing is that it is always unable to connect

**Comment by moody69420** [comment]
sounds like u need to reinstall the pack

**Comment by moody69420** [comment]
u should also update

**Comment by QQQQQQNB** [comment]
https://imgur.com/a/16tJSJE

This is a screenshot.I can only use this image hosting website for screenshots of network problems

**Comment by QQQQQQNB** [comment]
I updated and reinstalled many times

**Comment by LotP1** [comment]
sounds like an issue on the server then

**Comment by QQQQQQNB** [comment]
If I build a 1.16 server myself, then migrate the mos and config folders of this modpack. Can this work? I want to try

I see that the serverpack is different from the general one. I can't understand the mods folder

**Comment by QQQQQQNB** [comment]
sorry。 I have solved this problem. Because of my network, some mods are not downloaded automatically
