### ISSUE TITLE
Building Gadget places Dummy instead Machine

### ISSUE THREAD

**Issue by Okimo** [benbenlaw/techopolis#9]
When Building Gadget is used to place Fluid Absorber from Custom Machinery - Dummy block is placed instead
![2021-11-01_19 08 21](https://user-images.githubusercontent.com/12627805/139720724-bb1cecc9-9821-401f-bb54-794858041624.png)
![2021-11-01_19 14 39](https://user-images.githubusercontent.com/12627805/139720733-da20d663-19c4-498b-914a-56979600ca74.png)
.

**Comment by benbenlaw** [comment]
due to tile entites and building gadgets
